sudo:
  required

language: java
jdk: oraclejdk8

script: "mvn cobertura:cobertura"

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - raskidan@ya.ru