spring:
  liquibase:
    change-log: classpath:db-changelog.xml
  datasource:
    url: jdbc:h2:mem:shortener;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      path: /h2
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

shortener:
  prefix: http://localhost:8080/