name: build

on:
  push:
    branches:
    tags:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Submit coverage
        run: curl -s https://codecov.io/bash

      - name: Login into docker hub
        run: docker login -u ${{ secrets.D_USER }} -p ${{ secrets.D_PASS }}

      - name: Build and push docker images
        run: |
          export GIT_CURRENT_BRANCH=${GITHUB_REF##*/}
          export TAG=`if [ "$GIT_CURRENT_BRANCH" == "master" ]; then echo "latest"; else echo $GIT_CURRENT_BRANCH; fi`
          export DOCKER_IMAGE_NAME=eaxdev/urlshortener
          docker build -t $DOCKER_IMAGE_NAME:$TAG
          docker push $DOCKER_IMAGE_NAME:$TAG