name: build app

on:
  push:
    branches:
    tags:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: submit coverage
        run: curl -s https://codecov.io/bash
      - name: login into docker hub
        run: docker login -u ${{ secrets.$D_USER }} -p ${{ secrets.$D_PASS }}
      - name: set env variables
        run: |
          export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
          export GIT_BRANCH="${GITHUB_REF/refs\/heads\//}"
          echo 'print_branch'_$GIT_BRANCH
          echo 'print_branch2'_${GITHUB_REF##*/}